<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1">
<context>
    <name>Utils</name>
    <message>
      <location filename="../Utils.py" line="381"/>
      <source>space</source>
      <translation>espacio</translation>
    </message>
    <message>
      <location filename="../Utils.py" line="381"/>
      <source>converted to an underscore</source>
      <translation>convertido en un guion bajo</translation>
    </message>
    <message>
      <location filename="../Utils.py" line="382"/>
      <source>period</source>
      <translation>punto</translation>
    </message>
    <message>
      <location filename="../Utils.py" line="382"/>
      <source>removed</source>
      <translation>eliminado</translation>
    </message>
    <message>
      <location filename="../Utils.py" line="448"/>
      <source> - Copy</source>
      <translation> - Copia</translation>
    </message>
    <message>
      <location filename="../Utils.py" line="477"/>
      <source>Could not open the file {myFile} when converting to NFD.</source>
      <translation>No se pudo abrir el archivo {myFile} al convertir a NFD.</translation>
    </message>
    <message>
      <location filename="../Utils.py" line="656"/>
      <source>There was an error opening database: {DBname}. Perhaps the project is open and the sharing option under FieldWorks Project Properties has not been clicked.</source>
      <translation>Hubo un error al abrir la base de datos: {DBname}. Quizás el proyecto esté abierto y no se haya activado la opción de compartir en las Propiedades del Proyecto de FieldWorks.</translation>
    </message>
    <message>
      <location filename="../Utils.py" line="673"/>
      <source>The Target Database does not exist. Please check the configuration file.</source>
      <translation>La base de datos de destino no existe. Por favor, revise el archivo de configuración.</translation>
    </message>
    <message>
      <location filename="../Utils.py" line="680"/>
      <source>There was an error opening target database: {targetProj}. Perhaps the project is open and the sharing option under FieldWorks Project Properties has not been clicked.</source>
      <translation>Hubo un error al abrir la base de datos de destino: {targetProj}. Quizás el proyecto esté abierto y no se haya activado la opción de compartir en las Propiedades del Proyecto de FieldWorks.</translation>
    </message>
    <message>
      <location filename="../Utils.py" line="707"/>
      <source>source</source>
      <translation>fuente</translation>
    </message>
    <message>
      <location filename="../Utils.py" line="712"/>
      <source>target</source>
      <translation>destino</translation>
    </message>
    <message>
      <location filename="../Utils.py" line="777"/>
      <source>category</source>
      <translation>categoría</translation>
    </message>
    <message>
      <location filename="../Utils.py" line="796"/>
      <source>The abbreviation/name: &apos;{posAbbrStr}&apos; for {myType}: &apos;{posFullNameStr}&apos; can&apos;t have a {charName} in it. Could not complete, &apos;+                                            &apos;please correct this {myType} in the {dbType} database.</source>
      <translation>La abreviatura/nombre: '{posAbbrStr}' para {myType}: '{posFullNameStr}' no puede tener un {charName}. No se pudo completar, '+                                            'por favor, corrija este {myType} en la base de datos {dbType}.</translation>
    </message>
    <message>
      <location filename="../Utils.py" line="812"/>
      <source>The abbreviation/name: &apos;{oldAbbrStr}&apos; for {myType}: &apos;{posFullNameStr}&apos; in the {dbType} database can&apos;t have a {charName} in it. The {charName} &apos;+                                              &apos;has been {message}, forming {posAbbrStr}. Keep this in mind when referring to this {myType} in transfer rules.</source>
      <translation>La abreviatura/nombre: '{oldAbbrStr}' para {myType}: '{posFullNameStr}' en la base de datos {dbType} no puede tener un {charName}. El {charName} '+                                              'ha sido {message}, formando {posAbbrStr}. Tenga esto en cuenta al referirse a este {myType} en las reglas de transferencia.</translation>
    </message>
    <message>
      <location filename="../Utils.py" line="820"/>
      <source>Suppressing further warnings of this type.</source>
      <translation>Suprimiendo más advertencias de este tipo.</translation>
    </message>
    <message>
      <location filename="../Utils.py" line="957"/>
      <source>Invalid url link or url not found in the target database while processing source headword: {headWord}.</source>
      <translation>Enlace URL inválido o URL no encontrada en la base de datos de destino al procesar la palabra principal de origen: {headWord}.</translation>
    </message>
    <message>
      <location filename="../Utils.py" line="1071"/>
      <source>linked to entry: {headWordStr}, sense: {glossStr} in the {projectName} project.</source>
      <translation>vinculado a la entrada: {headWordStr}, significado: {glossStr} en el proyecto {projectName}.</translation>
    </message>
  </context>
</TS>
